initStore([
  {
    id: 0,
    title: 'Cyberpunk 2077: Ultimate Edition (PS5/Xbox)',
    description: 'Open-World-RPG mit der Phantom Liberty Erweiterung inklusive.',
    price: 79.99,
    discountPrice: 59.99,
    image: 'img/game-1.jpg',
  },
  {
    id: 1,
    title: 'Grand Theft Auto V (PS5)',
    description: 'Enthält GTA V Story-Modus und GTA Online mit PS5-Verbesserungen.',
    price: 49.99,
    discountPrice: 29.99,
    image: 'img/game-2.jpg',
  },
  {
    id: 2,
    title: 'Cyberpunk 2077: Phantom Liberty (DLC)',
    description: 'Spionage-Thriller Erweiterung für Cyberpunk 2077.',
    price: 39.99,
    discountPrice: 34.99,
    image: 'img/game-3.jpg',
  },
  {
    id: 3,
    title: 'EA Sports FC 24 (PS5)',
    description: 'Die neueste Fußballsimulation mit neuen Ligen und Mechaniken.',
    price: 69.99,
    discountPrice: 59.99,
    image: 'img/game-4.jpg',
  },
  {
    id: 4,
    title: 'The Last of Us Part I (PS5)',
    description: 'Neu aufgelegte Version des gefeierten Abenteuers in postapokalyptischer Welt.',
    price: 79.99,
    discountPrice: 49.99,
    image: 'img/game-5.jpg',
  },
  {
    id: 5,
    title: 'Hogwarts Legacy (PS5/Xbox)',
    description: 'Magisches Action-RPG im Harry-Potter-Universum mit offener Welt.',
    price: 69.99,
    discountPrice: 54.99,
    image: 'img/game-6.jpg',
  },
]);
